inmanta/pytest-inmanta

- examples/testmodule/model/_init.cf
- examples/testmodule/plugins/__init__.py
- examples/testmodule/tests/test_BadLog.py
- pytest_inmanta/plugin.py
- tests/test_basic_example.py
> added log serialization to fixtures

- CHANGELOG.md
- README.md
- examples/testmodule/tests/test_dryrun.py
- pytest_inmanta/plugin.py
- tests/test_basic_example.py
> added dryrun

- examples/testmodule/tests/test_capture.py
- examples/testmodule/tests/test_reset.py
- pytest_inmanta/plugin.py
- tests/test_basic_example.py
and ensured proper reset
fixes #4 and fixes #6
> removed custom io capturing

- pytest_inmanta/plugin.py
This issue will be fixed permanently in #21.
> Prevents IOError when using remote IO.

- examples/testmodule/tests/test_resource_run.py
- pytest_inmanta/plugin.py
> Expose scopes in project

- README.md
- pytest_inmanta/plugin.py
- tests/test_basic_example.py
did not add testcases, as this would be quite complex compared to the functionality
> Added --install_mode option

- examples/testhandler/tests/test_handler.py
- pytest_inmanta/plugin.py
- tests/test_handlers.py
> Return handler logs

- CHANGELOG.md
- README.md
- examples/testmodule/plugins/__init__.py
- examples/testmodule/tests/test_import.py
- pytest_inmanta/plugin.py
- tests/test_basic_example.py
The importing mechanism was implemented in inmanta/inmanta#507, this PR illustrates it with a test case.
Closes #37
> Support testing of regular functions and classes in modules

- CHANGELOG.md
- examples/testhandler/tests/test_handler.py
- pytest_inmanta/plugin.py
- tests/test_handlers.py
> Close handler caches properly

- CHANGELOG.md
- setup.py
> Bump version to v1.2.0

- CHANGELOG.md
- examples/testhandler/tests/test_dryrun.py
- pytest_inmanta/plugin.py
- tests/test_handlers.py
> Fixed status handling on dryrun

- CHANGELOG.md
- pytest_inmanta/plugin.py
- tests/test_options.py
> Add meaningful error message when --venv doesn't exist

- CHANGELOG.md
- examples/testhandler/tests/test_handler.py
- pytest_inmanta/plugin.py
> Close cache completely

- README.md
Document the compatibility issue that exists with the pytest-cov plugin.
closes inmanta/infra-tickets#25
> Document compatibility with pytest-cov

- requirements.txt
make dataclasses dep conditional
> make dataclasses dep conditional

- CHANGELOG.md
- examples/testhandler/tests/test_ignore_resource.py
- pytest_inmanta/module/init.cf
- pytest_inmanta/module/init.py
Added resource unittest::IgnoreResource
> Added resource unittest::IgnoreResource

- .bumpversion.cfg
- .ci-pyp.yml
- CHANGELOG.md
Automates release by using generic Jenkins file from inmanta/irt#236.
After merge, Jenkins job should be updated.
> automate release

- .ci-pyp.yml
> declare public in ci file

- CHANGELOG.md
- README.md
- pytest_inmanta/plugin.py
> Improve documentation of options

- requirements.txt
- setup.py
> reverted inmanta-core dependency change

- CHANGELOG.md
- requirements.txt
- setup.py
Remove dependency on the inmanta  package.
> Remove dependency on the inmanta package

- pytest_inmanta/plugin.py
- tests/test_basic_example.py
Fixes issue breaking project fixture 
> remove usage of internal compiler api

- CHANGELOG.md
- MANIFEST.in
- pytest_inmanta/plugin.py
Added types to pytest and add marker file for mypy
There a still a quite some type errors in here. 
> added typing and export types in the package

- pytest_inmanta/plugin.py
Quick compatibility fix for inmanta-core's master.
> hotfix: install modules prior to project load

- pytest_inmanta/plugin.py
quick fix for changes in core, may degrade performance
> also perform install on every compile

- examples/testhandler/tests/test_full_deploy.py
- pytest_inmanta/plugin.py
To my great embarrassment, my previos fix was also a broken fix, Now I did add testcases.  
> Third attempt to make it work

- tests/test_basic_example_v2.py
- tests/utils.py
I needed some of this functionality for `pytest-inmanta-lsm` so I made some better abstractions to have the same structure in both repos (just moved some things around). If we can't get around having some duplicate code, we better make sure there are as little differences as possible.
> Venv functions refactor

- README.md
Escape angle brackets so that they are correctly displayed
> [DOC] escape angle brackets so that they are correctly displayed

- CHANGELOG.md
- README.md
The option [was never added](https://github.com/inmanta/pytest-inmanta/pull/364#pullrequestreview-1311031266)
> dropped option from README

- tox.ini
add iso7 to tox as part of this ticket:
https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/gh/inmanta/infra-tickets/196
> add iso7 to tox

- CHANGELOG.md
- pytest_inmanta/plugin.py
> fix for changes on core

- CHANGELOG.md
- pytest_inmanta/plugin.py
- tox.ini
> Remove IO support

- CHANGELOG.md
- examples/testhandler/tests/test_handler.py
- pytest_inmanta/plugin.py
Add compatibility with iso8 reworked agent cache
> Add support for ISO8 AgentCache

- pytest_inmanta/test_parameter/path_parameter.py
> improve relative path for PathTestParameter

- tox.ini
part of inmanta/infra-tickets#121
> stop holding back virtualenv

- CHANGELOG.md
- README.md
- examples/refs/MANIFEST.in
- examples/refs/inmanta_plugins/refs/__init__.py
- examples/refs/model/_init.cf
- examples/refs/pyproject.toml
- examples/refs/setup.cfg
- examples/refs/tests/test_refs.py
- pytest_inmanta/core.py
- pytest_inmanta/plugin.py
- tests/test_references.py
> Added support for references
