pytest_inmanta/plugin.py

This removes a warning about yaml.load when using this pytest plugin. I don't think the extra functionality that yaml.load offers over yaml.safe_load is necessary to load the module.yml fille.

Change yaml.load to yaml.safe_load

---

examples/testmodule/tests/test_multiple_repo_paths.py
pytest_inmanta/plugin.py
tests/test_basic_example.py

Closes #38 
Specifying multiple repo paths is already possible, if they are separated by spaces.
Or should the separator be changed to comma?

Multiple repo paths

---

pytest_inmanta/plugin.py

Instead of raising a keyerror this raises a more comprehensible error

Improve the error message

---

CHANGELOG.md
pytest_inmanta/plugin.py

Unless specified otherwise (`no_dedent` parameter), the model provided to `project.compile` will be un-indented (we remove any space of tab at the beginning of lines if they are common to all the lines).
Before compiling the model, we log it (debug level), with line numbers.  (Makes it easier to debug error messages containing line numbers.)
closes #199 

project.compile logs the model with line numbers

---

pytest_inmanta/plugin.py

Set `no_dedent` argument of `project.compile()` to `True` by default to maintain backwards compatibility with `pytest-inmanta` version 1.5.2.

Set no_dedent argument of project.compile() to True by default

---

CHANGELOG.md
pytest_inmanta/plugin.py

Fixed ResourceIdStr import: this was previously imported from `inmanta.data` while it actually lives in `inmanta.data.model`.
I'm planning to do a patch release after merging.
closes inmanta/inmanta-core#3074

fixed ResourceIdStr import

---

CHANGELOG.md
pytest_inmanta/plugin.py
tests/conftest.py

Fixed issue with project fixture related to cleanup assumptions causing failures for `inmanta-core>=5.1.2.dev`. I'm planning to release this as a patch.

fixed project loading issue

---

examples/testmodule/tests/test_multiple_repo_paths.py

This test case made use of the internals of `Project`. It started failing after I merged inmanta/inmanta-core#3166 yesterday.
The new changes are not typed correctly in the same way the old ones weren't due to the way the `ModuleRepo` classes and methods are typed.

fixed test case making use of inmanta.module.Project internals

---

Jenkinsfile-integration-tests-iso3
tox.ini

* Add tox configuration to run the tests against ISO4 and master
* Add separate pipeline to run the tests against pytest-inmanta version used by the ISO3 product. 
closes inmanta/inmanta-core#3214

Add support to test pytest-inmanta against all ISO branches

---

tox.ini

Suggestion: always allow dev installs for `inmanta-core` for the `py36-inmmaster` environment. Currently this is only allowed when `PIP_PRE` is set. The pipelines on Jenkins do set it, so it doesn't cause any issues at the moment, except when running locally without setting `PIP_PRE`.

always allow dev install for inmanta-core master in tox config file

---

pytest_inmanta/plugin.py

Use absolute path for `INMANTA_TEST_ENV` symlink.
closes #252

INMANTA_TEST_ENV create symlink using absolute path

---

setup.cfg

I discovered while working on pytest-inmanta-lsm that the projects in examples would get inconsistent behavior from flake8 and black. The way we invoke black (with multiple directories) it always takes the config in this repo's root to be the authority, but flake8 did not do the same. In the case of pytest-inmanta there are currently no conflicts arising from this, but they might appear any time we make changes to or add new examples.
This pull request makes sure flake8-black always considers pytest-inmanta's root config to be the authority.
The option could also be set in the makefile as `--black-config`. I have no strong preference between the two.

fixed flake8 considering examples as separate projects with separate black config

---

CHANGELOG.md
pytest_inmanta/plugin.py

This PR fixes the bug where the temporary directory, used to store the Inmanta project, is not cleaned up when an exception occurs in the setup stage of the project_factory fixture.

Ensure temporary directories are cleaned up

---

examples/testmodule/tests/test_BadLog.py
tests/test_basic_example.py

Marked a test that is always expected to fail as `xfail`. I see the following benefits:
1. Keeps the exception trace out of the log on Jenkins. Having it there could give the impression that this is the root cause of a `pytest-inmanta` test failure, while it is actually the expected behavior.
2. Simplifies debugging: manually running this test (rather than the wrapping `pytest-inmanta` test), results in a successful run.
I didn't go to the effort of checking for all similar occurrences.

marked expected test failure as xfail

---

pytest_inmanta/plugin.py
tests/conftest.py

Added missing cleanup between pytest-inmanta (meta) tests. This caused subtle issues when the example projects being tested used different versions of the same module, specifically when the version that was installed first had a plugin that did not exist in the other version.
The `ProjectLoader` singleton manages plugin registration on the compiler to allow for top-level imports. To this end it caches any registered plugins in between compiles. For normal pytest-inmanta usage this is valid because all compiles are based on the same project, with the same requirements, in the same venv. The pytest-inmanta test suite howeve triggers multiple `pytest` runs on different modules (unless `--runpytest=subprocess` is set). In this case, this singleton state is still valid between compiles for a …

Fixed test cleanup issue

---

CHANGELOG.md
README.md
examples/testhandler/tests/test_dryrun.py
examples/testhandler/tests/test_full_deploy.py
pytest_inmanta/module/init.cf
pytest_inmanta/module/init.py
pytest_inmanta/plugin.py
tests/test_handlers.py

Added a function to dryrun every resource and do some sanity checks.
Added another function to do a dryrun followed by a deploy and another dryrun. 
These workflows are used a lot in testing and these functions would eliminate a lot of boilerplate code.
Still missing some documentation
closes #358

Added dryrun_all and dryrun_and_deploy_all

---

tox.ini

Add version constraint `virtualenv<20.22.0` to the tox config. Newer version of virtualenv don't have support anymore to create a python3.6 venv. In that case we get the following error:
```
Error processing line 1 of /home/jenkins/workspace/ment-tools_pytest-inmanta_master/pytest-inmanta/.tox/py36-inmiso4/lib/python3.6/site-packages/_virtualenv.pth:
Traceback (most recent call last):
File "/usr/lib64/python3.6/site.py", line 168, in addpackage
exec(line)
File "<string>", line 1, in <module>
File "/home/jenkins/workspace/ment-tools_pytest-inmanta_master/pytest-inmanta/.tox/py36-inmiso4/lib/python3.6/site-packages/_virtualenv.py", line 3
from __future__ import annotations
^
SyntaxError: future feature annotations is not defined
Remainder of file ignored
Error processing line 1 of …
```

Add a version constraint on the virtualenv dependency

---

CHANGELOG.md
pytest_inmanta/core.py
pytest_inmanta/plugin.py
tests/test_dependencies.py

As discussed [here](https://inmanta.slack.com/archives/CKRF0C8R3/p1688386956424409?thread_ts=1688132643.347189&cid=CKRF0C8R3):
> 1. on iso6, if you use --pip-index-url pytest-inmanta logs a warning that a project-wide pip index url is not supported on this version of inmanta-core and that it will use the index as a v2 package source instead.
> 2. on iso7+, stick with the current warning
> Wdyt? We should update the changelog note in that case.

[FIX] make new behaviour iso7+ only

---

pytest_inmanta/parameters.py
pytest_inmanta/plugin.py
pytest_inmanta/test_parameter/list_parameter.py
pytest_inmanta/test_parameter/parameter.py
tests/test_dependencies.py

closes https://github.com/inmanta/pytest-inmanta/issues/404

[WIP] update warning message

---

pytest_inmanta/plugin.py

When runngin mypy on a module using the `Result` object of pytest_inmanta, I got type checking errors because the return annotations of `deploy_all` was actually `protocol.Result`.
This PR fixes this.

protocol.Result shadows pytest_inmanta.plugin.Result

---

CHANGELOG.md
pytest_inmanta/test_parameter/boolean_parameter.py

Allow more options for boolean test parameters
closes https://github.com/inmanta/pytest-inmanta/issues/432

Allow more options for boolean test parameters

---

CHANGELOG.md
examples/testhandler/tests/test_dryrun.py
examples/testhandler/tests/test_get_resource_subtle_case.py
examples/testhandler/tests/test_handler.py
examples/testhandler/tests/test_ignore_resource.py
pytest_inmanta/module/init.cf
pytest_inmanta/module/init.py
pytest_inmanta/plugin.py
tests/test_basic_example.py

- Added `Project.get_one_resource` method to have a stricter filtering
- Added strict mode on `Project.get_resource` method (if set to `True`, will internally call get_one_resource)
closes https://github.com/inmanta/pytest-inmanta/issues/468

Add stricter get_resource method

---

CHANGELOG.md
README.md
pytest_inmanta/plugin.py
tests/test_basic_example_v2.py

Switch deprecated `inmanta module install -e .` to `pip install -e .` in error reporting.
Do we need a changelog entry for this?
closes #518 

Remove reference to deprecated module install command

---

CHANGELOG.md
pytest_inmanta/plugin.py

Fix incompatibility with versions of inmanta-core that have support to push environment settings to the server.
Related to https://github.com/inmanta/inmanta-core/pull/9355

Fix incompatibility inmanta-core: push environment settings
